# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    #-   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: forbid-new-submodules
    #-   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args: ["--branch=main"]


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [
          --ignore-missing-imports,
          --no-strict-optional,
          --config-file=./pyproject.toml
        ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--config=./pyproject.toml,--fix,--exit-non-zero-on-fix]
