name: Build, Test , Publish

on:
    pull_request:
        types: [opened,synchronize]
    push:
        branches:
            - main

jobs:
    build-test-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.8
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        - name: buid
          run: |
            ./run.sh install
            ./run.sh build
            ./run.sh publish:test
        # - name: Install dependencies
        #   run: |
        #     python -m pip install --upgrade pip
        #     pip install pre-commit
        # - name: Analysing the code with pre-commit
        #   run: |
        #     pre-commit run --all-files
        #     echo $(git ls-files '*.py')
