name: Build, Test , Publish

on:
    pull_request:
        types: [opened,synchronize]
    push:
        branches:
            - main


jobs:
    one:
        runs-on: ubuntu-16.04
        steps:
          - name: Dump GitHub context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"
          - name: Dump job context
            env:
              JOB_CONTEXT: ${{ toJson(job) }}
            run: echo "$JOB_CONTEXT"
          - name: Dump steps context
            env:
              STEPS_CONTEXT: ${{ toJson(steps) }}
            run: echo "$STEPS_CONTEXT"
          - name: Dump runner context
            env:
              RUNNER_CONTEXT: ${{ toJson(runner) }}
            run: echo "$RUNNER_CONTEXT"
          - name: Dump strategy context
            env:
              STRATEGY_CONTEXT: ${{ toJson(strategy) }}
            run: echo "$STRATEGY_CONTEXT"
          - name: Dump matrix context
            env:
              MATRIX_CONTEXT: ${{ toJson(matrix) }}
            run: echo "$MATRIX_CONTEXT"
    build-test-and-publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.8
          uses: actions/setup-python@v3
          with:
            python-version: 3.8
        - name: buid
          run: |
            ./run.sh install
            ./run.sh build
            ./run.sh publish:test
        #   env:
        #     TEST_PYPI_TOKEN:
        # - name: Install dependencies
        #   run: |
        #     python -m pip install --upgrade pip
        #     pip install pre-commit
        # - name: Analysing the code with pre-commit
        #   run: |
        #     pre-commit run --all-files
        #     echo $(git ls-files '*.py')
